"use client";

import { LegalShell, PlaceholderValue } from "@/app/components/LegalShell";
import { useI18n } from "@/lib/i18n-context";
import { asondoData } from "@/lib/asondo-data";

export default function DDSPage() {
  const { locale } = useI18n();
  const fr = locale === "fr";

  return (
    <LegalShell
      bgImage="/photo1.jpg"
      eyebrow="EUDR · Annex II / Article 4"
      title={
        fr
          ? "Déclaration de Diligence Raisonnée (DDS)"
          : "Due Diligence Statement (DDS)"
      }
      subtitle={
        fr
          ? "Modèle de la déclaration soumise par Asondo au système d'information EUDR pour chaque expédition vers l'Union européenne. Les valeurs marquées « à compléter » sont remplies par expédition."
          : "Template of the statement submitted by Asondo to the EUDR information system for each shipment to the European Union. Values marked “to be filled” are populated per shipment."
      }
      lastUpdated="2026-05-11"
    >
      <blockquote>
        {fr
          ? "Cette page présente le modèle public de notre DDS. Les déclarations réelles, leurs numéros de référence (DDS Reference Number) et leurs polygones GPS détaillés sont communiqués aux acheteurs vérifiés sous NDA, dans le Buyer Pack."
          : "This page presents the public template of our DDS. Actual statements, their reference numbers (DDS Reference Number) and detailed GPS polygons are shared with verified buyers under NDA, in the Buyer Pack."}
      </blockquote>

      <h2>
        {fr ? "1. Identification de l'opérateur" : "1. Operator identification"}
      </h2>
      <ul>
        <li>
          <strong>{fr ? "Raison sociale" : "Company name"} :</strong>{" "}
          {asondoData.identity.legalName}
        </li>
        <li>
          <strong>{fr ? "Forme juridique" : "Legal form"} :</strong>{" "}
          {fr ? asondoData.legal.legalForm : asondoData.legal.legalFormEn}
        </li>
        <li>
          <strong>{fr ? "Adresse" : "Address"} :</strong>{" "}
          {asondoData.identity.streetAddress} —{" "}
          {asondoData.identity.postalBox}, {asondoData.identity.city},{" "}
          {asondoData.identity.country}
        </li>
        <li>
          <strong>RCCM :</strong> {asondoData.legal.rccm}
        </li>
        <li>
          <strong>EORI / TIN :</strong>{" "}
          <PlaceholderValue>
            {fr
              ? "à compléter (numéro identification opérateur EUDR)"
              : "to be filled (EUDR operator ID)"}
          </PlaceholderValue>
        </li>
        <li>
          <strong>{fr ? "Représentant autorisé" : "Authorised representative"} :</strong>{" "}
          {asondoData.leadership.ceoName} —{" "}
          {fr
            ? asondoData.leadership.ceoRole
            : asondoData.leadership.ceoRoleEn}
          , {asondoData.identity.legalName}
        </li>
        <li>
          <strong>
            {fr ? "Responsable Conformité EUDR" : "EUDR Compliance Officer"} :
          </strong>{" "}
          <a href="/eudr/compliance-officer">
            {fr ? "voir page dédiée" : "see dedicated page"}
          </a>
        </li>
      </ul>

      <h2>
        {fr ? "2. Numéro de référence DDS" : "2. DDS reference number"}
      </h2>
      <ul>
        <li>
          <strong>{fr ? "DDS Reference Number" : "DDS Reference Number"} :</strong>{" "}
          <PlaceholderValue>
            {fr
              ? "ASD-DDS-YYYY-NNNN (généré par EUDR IS)"
              : "ASD-DDS-YYYY-NNNN (generated by EUDR IS)"}
          </PlaceholderValue>
        </li>
        <li>
          <strong>
            {fr ? "DDS Verification Number" : "DDS Verification Number"} :
          </strong>{" "}
          <PlaceholderValue>
            {fr ? "à compléter" : "to be filled"}
          </PlaceholderValue>
        </li>
        <li>
          <strong>{fr ? "Date de soumission" : "Submission date"} :</strong>{" "}
          <PlaceholderValue>
            {fr ? "ISO-8601 par expédition" : "ISO-8601 per shipment"}
          </PlaceholderValue>
        </li>
      </ul>

      <h2>{fr ? "3. Description du produit" : "3. Product description"}</h2>
      <table>
        <tbody>
          <tr>
            <th>{fr ? "Désignation" : "Designation"}</th>
            <td>
              {fr
                ? "Fèves de cacao brutes ou torréfiées, entières ou brisées"
                : "Cocoa beans, whole or broken, raw or roasted"}
            </td>
          </tr>
          <tr>
            <th>{fr ? "Code SH" : "HS code"}</th>
            <td>1801 00 00</td>
          </tr>
          <tr>
            <th>{fr ? "Nom commun" : "Common name"}</th>
            <td>{fr ? "Cacao en fèves" : "Cocoa beans"}</td>
          </tr>
          <tr>
            <th>{fr ? "Nom scientifique" : "Scientific name"}</th>
            <td>
              <em>Theobroma cacao</em> L.
            </td>
          </tr>
          <tr>
            <th>{fr ? "Quantité" : "Quantity"}</th>
            <td>
              <PlaceholderValue>
                {fr ? "kg / tonnes par expédition" : "kg / metric tons per shipment"}
              </PlaceholderValue>
            </td>
          </tr>
          <tr>
            <th>{fr ? "Conditionnement" : "Packaging"}</th>
            <td>
              {fr
                ? "Sacs de jute 60–65 kg ou conteneurs vrac selon contrat"
                : "Jute bags 60–65 kg or bulk containers per contract"}
            </td>
          </tr>
        </tbody>
      </table>

      <h2>{fr ? "4. Pays de production" : "4. Country of production"}</h2>
      <ul>
        <li>
          <strong>ISO 3166-1 :</strong> CI ({fr ? "Côte d'Ivoire" : "Côte d'Ivoire"})
        </li>
        <li>
          <strong>{fr ? "Régions de sourcing" : "Sourcing regions"} :</strong>{" "}
          {fr
            ? "Bassin Centre (Bouaké / Yamoussoukro), Bassin Est (Abengourou / Aboisso), Bassin Ouest (Daloa / San-Pédro)"
            : "Central basin (Bouaké / Yamoussoukro), Eastern basin (Abengourou / Aboisso), Western basin (Daloa / San-Pédro)"}
        </li>
      </ul>

      <h2>
        {fr
          ? "5. Géolocalisation des parcelles (polygones)"
          : "5. Plot geolocation (polygons)"}
      </h2>
      <p>
        {fr
          ? "Conformément à l'article 9 du Règlement (UE) 2023/1115, chaque parcelle de production est identifiée par un polygone GPS (latitude / longitude) lorsque la surface dépasse 4 hectares, ou par un point géoréférencé pour les parcelles plus petites. Les polygones complets sont annexés à la DDS soumise à l'EUDR IS."
          : "In accordance with Article 9 of Regulation (EU) 2023/1115, each production plot is identified by a GPS polygon (latitude / longitude) when the area exceeds 4 hectares, or by a geo-referenced point for smaller plots. Full polygons are annexed to the DDS submitted to the EUDR IS."}
      </p>
      <ul>
        <li>
          {fr
            ? "Format des polygones : GeoJSON (RFC 7946), précision ≤ 10 mètres"
            : "Polygon format: GeoJSON (RFC 7946), accuracy ≤ 10 metres"}
        </li>
        <li>
          {fr
            ? "Échantillon anonymisé public : voir la"
            : "Public anonymised sample: see the"}{" "}
          <a href="/reseau">
            {fr ? "carte réseau" : "network map"}
          </a>{" "}
          {fr
            ? "(superposition « polygone démo »)"
            : "(“demo polygon” overlay)"}
        </li>
        <li>
          {fr
            ? "Polygones complets : disponibles aux acheteurs vérifiés sous NDA via le Buyer Pack"
            : "Full polygons: available to verified buyers under NDA via the Buyer Pack"}
        </li>
      </ul>

      <h2>{fr ? "6. Date de production" : "6. Time of production"}</h2>
      <p>
        {fr
          ? "Période de récolte couverte par chaque expédition : campagne principale (octobre–mars) ou campagne intermédiaire (avril–septembre), précisée pour chaque DDS."
          : "Harvest period covered by each shipment: main crop (October–March) or mid-crop (April–September), specified for each DDS."}
      </p>
      <ul>
        <li>
          <strong>{fr ? "Saison" : "Season"} :</strong>{" "}
          <PlaceholderValue>
            {fr ? "Main / Mid-crop YYYY/YY" : "Main / Mid-crop YYYY/YY"}
          </PlaceholderValue>
        </li>
        <li>
          <strong>{fr ? "Date butoir EUDR" : "EUDR cut-off date"} :</strong>{" "}
          {fr
            ? "31 décembre 2020 — aucune déforestation postérieure tolérée"
            : "31 December 2020 — no post-cut-off deforestation tolerated"}
        </li>
      </ul>

      <h2>
        {fr
          ? "7. Évaluation des risques et mesures d'atténuation"
          : "7. Risk assessment and mitigation measures"}
      </h2>
      <p>
        {fr
          ? "Pour chaque expédition, Asondo conduit l'évaluation des risques en croisant les polygones avec les sources cartographiques de référence (Hansen Global Forest Change v1.x, JRC TMF, ECA Whisp). Les indicateurs suivis :"
          : "For each shipment, Asondo conducts the risk assessment by cross-referencing polygons with reference cartographic sources (Hansen Global Forest Change v1.x, JRC TMF, ECA Whisp). Indicators monitored:"}
      </p>
      <ul>
        <li>{fr ? "Couvert forestier au 31/12/2020" : "Forest cover as of 31/12/2020"}</li>
        <li>
          {fr
            ? "Pertes de couvert depuis la date butoir"
            : "Cover loss since the cut-off date"}
        </li>
        <li>
          {fr
            ? "Légalité de la production (cadre foncier, droits coutumiers, droit du travail, droits humains, fiscalité)"
            : "Production legality (land tenure, customary rights, labour law, human rights, taxation)"}
        </li>
        <li>
          {fr
            ? "Profil du producteur et de la coopérative"
            : "Producer and cooperative profile"}
        </li>
      </ul>
      <p>
        {fr
          ? "Si le risque évalué n'est pas négligeable, Asondo met en œuvre les mesures d'atténuation et n'expédie pas tant que le risque n'est pas redescendu à un niveau négligeable."
          : "If the assessed risk is not negligible, Asondo implements mitigation measures and does not ship until the risk is reduced to a negligible level."}
      </p>

      <h2>{fr ? "8. Déclaration formelle" : "8. Formal declaration"}</h2>
      <blockquote>
        {fr
          ? "Le soussigné, représentant autorisé de ASONDO SA, atteste que la diligence raisonnée a été exercée conformément au Règlement (UE) 2023/1115, qu'aucune déforestation ni dégradation forestière n'a eu lieu sur les parcelles concernées après le 31 décembre 2020, que la production est légale au regard du droit ivoirien, et que le risque de non-conformité est négligeable."
          : "The undersigned, authorised representative of ASONDO SA, attests that due diligence has been exercised in accordance with Regulation (EU) 2023/1115, that no deforestation or forest degradation has occurred on the relevant plots after 31 December 2020, that production is lawful under Ivorian law, and that the risk of non-compliance is negligible."}
      </blockquote>

      <h2>{fr ? "9. Signatures" : "9. Signatures"}</h2>
      <ul>
        <li>
          <strong>
            {fr ? "Représentant autorisé" : "Authorised representative"} :
          </strong>{" "}
          {asondoData.leadership.ceoName} —{" "}
          {fr
            ? asondoData.leadership.ceoRole
            : asondoData.leadership.ceoRoleEn}
          , {asondoData.identity.legalName}{" "}
          —{" "}
          <PlaceholderValue>
            {fr ? "signature électronique qualifiée" : "qualified electronic signature"}
          </PlaceholderValue>
        </li>
        <li>
          <strong>
            {fr ? "Responsable Conformité EUDR" : "EUDR Compliance Officer"} :
          </strong>{" "}
          <PlaceholderValue>
            {fr ? "à compléter — signature jointe à la DDS" : "to be filled — signature attached to DDS"}
          </PlaceholderValue>
        </li>
        <li>
          <strong>{fr ? "Date" : "Date"} :</strong>{" "}
          <PlaceholderValue>
            {fr ? "ISO-8601 par expédition" : "ISO-8601 per shipment"}
          </PlaceholderValue>
        </li>
      </ul>

      <h2>{fr ? "10. Téléchargement & accès" : "10. Download & access"}</h2>
      <p>
        {fr
          ? "Le PDF de la DDS spécifique à votre expédition est mis à disposition après signature du Buyer Pack et confirmation contractuelle. Le numéro de référence DDS vous est communiqué par email avant la mise sur le marché de l'Union."
          : "The DDS PDF specific to your shipment is made available after the Buyer Pack is signed and the contract is confirmed. The DDS reference number is provided by email before placing on the EU market."}
      </p>
      <p>
        {fr ? "Demande d'accès :" : "Access request:"}{" "}
        <a href="/contact">
          {fr ? "Demander un Buyer Pack" : "Request a Buyer Pack"}
        </a>{" "}
        ·{" "}
        <a href="mailto:compliance@asondo.ci">
          compliance@asondo.ci
        </a>
      </p>
    </LegalShell>
  );
}
