import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { I18nProvider } from "@/lib/i18n-context";
import { SiteReadyGate } from "@/app/components/SiteReadyGate";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: {
    default: "Asondo, Votre Exportateur de Cacao Ivoirien | EUDR-Ready",
    template: "%s · Asondo",
  },
  description:
    "Asondo : votre exportateur de cacao ivoirien. Engagés pour une filière durable et compétitive. 15 ans d'expérience, lien direct avec les coopératives de petits producteurs, traçabilité complète et conformité EUDR.",
  keywords: [
    "cacao",
    "cocoa",
    "Côte d'Ivoire",
    "Ivory Coast",
    "Asondo",
    "EUDR",
    "exportateur",
    "exporter",
    "traçabilité",
    "traceability",
    "durable",
    "sustainable",
    "CCC",
    "Conseil du Café-Cacao",
    "Abidjan",
    "fèves de cacao",
    "cocoa beans",
    "FOB",
    "CIF",
  ],
  authors: [{ name: "Asondo SA", url: "https://asondo.ci" }],
  creator: "Asondo SA",
  publisher: "Asondo SA",
  metadataBase: new URL("https://asondo.ci"),
  alternates: {
    canonical: "/",
    languages: {
      fr: "/",
      en: "/",
    },
  },
  openGraph: {
    title: "Asondo, Votre Exportateur de Cacao Ivoirien",
    description:
      "Cacao ivoirien traçable et durable, en lien direct avec les coopératives de petits producteurs. Conformité EUDR.",
    type: "website",
    locale: "fr_FR",
    alternateLocale: "en_US",
    siteName: "Asondo",
    url: "https://asondo.ci",
    // The actual `og:image` is generated by `app/opengraph-image.tsx`
    // (Next.js file-system metadata convention) so no `images` field
    // is needed here. Leaving it out also prevents accidental
    // duplication with a different aspect ratio.
  },
  twitter: {
    card: "summary_large_image",
    title: "Asondo, Votre Exportateur de Cacao Ivoirien",
    description: "Cacao ivoirien traçable et durable. EUDR-Ready.",
    site: "@asondo_ci",
    creator: "@asondo_ci",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  category: "Business",
};

/**
 * Root layout: provides global HTML chrome, fonts, providers, and the
 * Sonner toaster. The public site adds its own Navbar/Footer in
 * `app/(site)/layout.tsx`. The CEO console provides its own chrome in
 * `app/console/(authed)/layout.tsx` and `app/console/login/layout.tsx`.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={inter.variable}>
      <body className={`${inter.className} antialiased bg-[#FDFBF7] text-[#1A1A1A]`}>
        {/*
         * Server-rendered initial splash. Sits as a sibling of the
         * React tree so it appears on the very first paint, before
         * any client component hydrates. The <SiteReadyGate /> below
         * removes it once `window.load`, `document.fonts.ready` and
         * the critical-asset preloads have all resolved. See
         * `globals.css` for the styling.
         */}
        <div id="site-loader" aria-hidden="true">
          <div className="site-loader__brand">
            <span className="site-loader__name">asondo</span>
            <span className="site-loader__tag">Cocoa Export OS</span>
          </div>
          <div className="site-loader__spinner" aria-hidden="true" />
        </div>
        <SiteReadyGate />

        <I18nProvider>{children}</I18nProvider>
        <Toaster
          position="top-right"
          richColors
          closeButton
          toastOptions={{
            style: {
              fontFamily: "var(--font-inter), system-ui, sans-serif",
            },
          }}
        />
      </body>
    </html>
  );
}
