import type { MetadataRoute } from "next";

/**
 * `/robots.txt` is generated by Next.js from this file. Keep it in
 * sync with the `app/sitemap.ts` URL — both must agree on the
 * canonical host name (asondo.ci, no trailing slash).
 *
 * The `/console/*` namespace is intentionally disallowed: it is the
 * private CEO console behind authentication and should never appear
 * in search results, even though the middleware already blocks
 * unauthenticated traffic.
 */
const SITE_URL = "https://asondo.ci";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/console", "/console/", "/api/"],
      },
      {
        // Block AI scrapers from training on our published evidence
        // until we publish a formal data-licensing position.
        userAgent: ["GPTBot", "ClaudeBot", "Google-Extended", "CCBot"],
        disallow: "/",
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
