import type { MetadataRoute } from "next";

/**
 * `/sitemap.xml` is generated by Next.js from this file. The list is
 * intentionally hand-maintained: every public route here must exist
 * as a real page under `app/(site)/`. Add new entries when you ship
 * new public pages, and remove entries when a page is retired.
 *
 * Routes under `/console/*` are private and must NEVER be listed.
 */
const SITE_URL = "https://asondo.ci";

type Entry = {
  path: string;
  changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"];
  priority: number;
};

const ENTRIES: Entry[] = [
  // Marketing
  { path: "/", changeFrequency: "weekly", priority: 1.0 },

  // Topical pages (Phase D)
  { path: "/eudr", changeFrequency: "weekly", priority: 0.9 },
  { path: "/programme", changeFrequency: "monthly", priority: 0.8 },
  { path: "/reseau", changeFrequency: "monthly", priority: 0.8 },
  { path: "/equipe", changeFrequency: "monthly", priority: 0.7 },
  { path: "/contact", changeFrequency: "monthly", priority: 0.7 },

  // EUDR sub-pages (Phase C)
  {
    path: "/eudr/compliance-officer",
    changeFrequency: "yearly",
    priority: 0.6,
  },
  {
    path: "/eudr/due-diligence-statement",
    changeFrequency: "yearly",
    priority: 0.6,
  },

  // Legal (Phase C)
  { path: "/legal/mentions-legales", changeFrequency: "yearly", priority: 0.4 },
  {
    path: "/legal/confidentialite",
    changeFrequency: "yearly",
    priority: 0.4,
  },
  { path: "/legal/cgu", changeFrequency: "yearly", priority: 0.4 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  return ENTRIES.map(({ path, changeFrequency, priority }) => ({
    url: `${SITE_URL}${path}`,
    lastModified,
    changeFrequency,
    priority,
    alternates: {
      languages: {
        fr: `${SITE_URL}${path}`,
        en: `${SITE_URL}${path}`,
      },
    },
  }));
}
